In [1]:
import pandas as pd
from pathlib import Path

In [3]:
# Store filepath in a variable
file = Path("owid-covid-data.csv")
file_df = pd.read_csv(file)
file_df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,NaN,0.0,NaN,NaN,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302507,ZWE,Africa,Zimbabwe,2023-04-08,264578.0,2.0,4.143,5684.0,1.0,0.571,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
302508,ZWE,Africa,Zimbabwe,2023-04-09,264582.0,4.0,4.714,5684.0,0.0,0.571,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
302509,ZWE,Africa,Zimbabwe,2023-04-10,264584.0,2.0,4.143,5684.0,0.0,0.571,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
302510,ZWE,Africa,Zimbabwe,2023-04-11,264584.0,0.0,3.143,5684.0,0.0,0.571,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN
302511,ZWE,Africa,Zimbabwe,2023-04-12,264584.0,0.0,2.571,5684.0,0.0,0.429,...,30.7,36.791,1.7,61.49,0.571,16320539.0,NaN,NaN,NaN,NaN

In [8]:
files_df = file_df[['continent', 'location', 'date','population', 'total_cases', 'total_deaths', 'total_cases','icu_patients', 'hosp_patients', 'total_tests', 'positive_rate', 'tests_units','people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'population_density', 'median_age', 'aged_65_older','aged_70_older','gdp_per_capita','cardiovasc_death_rate','diabetes_prevalence']]
filies_df = files_df.dropna(how='any')
filies_df

,continent,location,date,population,total_cases,total_deaths,total_cases,icu_patients,hosp_patients,total_tests,...,people_vaccinated,people_fully_vaccinated,total_boosters,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence
16193,Oceania,Australia,2021-10-07,26177410.0,117770.0,1470.0,117770.0,293.0,1522.0,39191561.0,...,17408468.0,12503241.0,151.0,3.202,37.9,15.504,10.129,44648.710,107.791,5.07
16194,Oceania,Australia,2021-10-08,26177410.0,120043.0,1493.0,120043.0,287.0,1437.0,39403312.0,...,17521126.0,12720856.0,292.0,3.202,37.9,15.504,10.129,44648.710,107.791,5.07
16195,Oceania,Australia,2021-10-09,26177410.0,122506.0,1504.0,122506.0,293.0,1446.0,39581452.0,...,17593798.0,12883681.0,433.0,3.202,37.9,15.504,10.129,44648.710,107.791,5.07
16196,Oceania,Australia,2021-10-10,26177410.0,125051.0,1526.0,125051.0,296.0,1492.0,39758570.0,...,17644750.0,12998286.0,481.0,3.202,37.9,15.504,10.129,44648.710,107.791,5.07
16197,Oceania,Australia,2021-10-11,26177410.0,127423.0,1541.0,127423.0,309.0,1486.0,39943975.0,...,17742605.0,13212457.0,715.0,3.202,37.9,15.504,10.129,44648.710,107.791,5.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
285560,North America,United States,2022-06-14,338289856.0,84664970.0,1002944.0,84664970.0,2999.0,26042.0,911039148.0,...,259353061.0,223029633.0,123139146.0,35.608,38.3,15.413,9.732,54225.446,151.089,10.79
285561,North America,United States,2022-06-15,338289856.0,84756328.0,1003230.0,84756328.0,2994.0,26413.0,911642612.0,...,259394474.0,223064339.0,123335005.0,35.608,38.3,15.413,9.732,54225.446,151.089,10.79
285562,North America,United States,2022-06-16,338289856.0,84894338.0,1003649.0,84894338.0,3043.0,26235.0,912115224.0,...,259435866.0,223097999.0,123529208.0,35.608,38.3,15.413,9.732,54225.446,151.089,10.79
285563,North America,United States,2022-06-17,338289856.0,85037513.0,1004218.0,85037513.0,2996.0,26221.0,912521698.0,...,259479523.0,223134513.0,123733694.0,35.608,38.3,15.413,9.732,54225.446,151.089,10.79
285564,North America,United States,2022-06-18,338289856.0,85135087.0,1004519.0,85135087.0,2925.0,25557.0,912769124.0,...,259502335.0,223152482.0,123816787.0,35.608,38.3,15.413,9.732,54225.446,151.089,10.79